export const UPDATE_ROOM = 'UPDATE_ROOM'
export const SET_USER = 'SET_USER'
export const UNSET_USER = 'UNSET_USER'
export const SET_CONFIG = 'SET_CONFIG'
export const ENTER_ROOM = 'ENTER_ROOM'
export const RESET_ROOM = 'RESET_ROOM'
